name: Ruby Gem Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build + Tests + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    env:
      BELPOST_API_URL: https://testapi.belpost.by
      BELPOST_JWT_TOKEN: test-token-for-ci
      BELPOST_TIMEOUT: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true

    - name: Run tests
      run: |
        bundle install
        bundle exec rspec
        
    - name: Build and Publish Gem
      uses: dawidd6/action-publish-gem@v1
      with:
        api_key: ${{ secrets.RUBYGEMS_API_KEY }} 