name: Ruby Gem Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true

    - name: Run tests
      run: |
        bundle install
        bundle exec rspec

    - name: Build and Publish Gem
      uses: dawidd6/action-publish-gem@v1
      with:
        api_key: ${{ secrets.RUBYGEMS_API_KEY }} 